# Generated by Django 5.2.17 on 2026-09-18 08:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_documentsectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_snapshots', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DashboardSourceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(db_index=True, max_length=100)),
                ('row_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payload', models.JSONField(default=dict, help_text='Celdas originales de la fila, incluyendo valor cacheado, fórmula y formato cuando existen.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rows', to='dashboard.dashboardsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('snapshot', 'sheet_name', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='ObjectiveAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matrix_type', models.CharField(choices=[('oee_osi', 'OEE vs OSI'), ('epi_osi', 'EPI vs OSI')], db_index=True, max_length=20)),
                ('source_row', models.PositiveIntegerField()),
                ('source_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_group', models.CharField(blank=True, max_length=180)),
                ('source_description', models.TextField(blank=True)),
                ('objective_code', models.CharField(db_index=True, max_length=30)),
                ('relation_type', models.CharField(choices=[('P', 'Principal'), ('S', 'Secundaria')], db_index=True, max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_alignments', to='dashboard.dashboardsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('snapshot', 'matrix_type', 'source_row', 'objective_code'),
            },
        ),
        migrations.CreateModel(
            name='SecurityObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.PositiveIntegerField()),
                ('measurement_id', models.CharField(db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('method_resources', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=180)),
                ('calculation_period', models.CharField(blank=True, max_length=120)),
                ('indicator', models.CharField(blank=True, max_length=120)),
                ('current_value_raw', models.CharField(blank=True, max_length=120)),
                ('current_value_numeric', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('current_number_format', models.CharField(blank=True, max_length=120)),
                ('calculation_formula', models.TextField(blank=True)),
                ('compliance_raw', models.CharField(blank=True, db_index=True, max_length=30)),
                ('compliance_formula', models.TextField(blank=True)),
                ('source_compliance_override', models.CharField(blank=True, help_text='Valor adicional de la columna I del Dashboard OESI, preservado sin reinterpretación.', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_objectives', to='dashboard.dashboardsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('snapshot', 'source_row'),
            },
        ),
        migrations.CreateModel(
            name='SGSIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.PositiveIntegerField()),
                ('measurement_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('pdca_cycle', models.CharField(blank=True, max_length=10)),
                ('sgsi_process', models.TextField(blank=True)),
                ('method_resources', models.TextField(blank=True)),
                ('measurement_objective', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=180)),
                ('update_period', models.CharField(blank=True, max_length=120)),
                ('indicator', models.CharField(blank=True, max_length=120)),
                ('current_value_raw', models.CharField(blank=True, max_length=120)),
                ('current_value_numeric', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('current_number_format', models.CharField(blank=True, max_length=120)),
                ('calculation_formula', models.TextField(blank=True)),
                ('compliance_raw', models.CharField(blank=True, db_index=True, max_length=30)),
                ('compliance_formula', models.TextField(blank=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sgsi_metrics', to='dashboard.dashboardsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('snapshot', 'source_row'),
            },
        ),
        migrations.CreateModel(
            name='StrategicFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor_type', models.CharField(choices=[('internal', 'Interno / MEFI'), ('external', 'Externo / MEFE')], db_index=True, max_length=16)),
                ('category', models.CharField(blank=True, db_index=True, max_length=40)),
                ('factor', models.TextField()),
                ('classification', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('source_row', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_factors', to='dashboard.dashboardsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('snapshot', 'factor_type', 'source_row'),
            },
        ),
        migrations.AddConstraint(
            model_name='dashboardsnapshot',
            constraint=models.UniqueConstraint(fields=('year', 'source_sha256'), name='uniq_dashboard_year_sha'),
        ),
        migrations.AddConstraint(
            model_name='dashboardsourcerow',
            constraint=models.UniqueConstraint(fields=('snapshot', 'sheet_name', 'row_number'), name='uniq_dashboard_source_row'),
        ),
        migrations.AddConstraint(
            model_name='objectivealignment',
            constraint=models.UniqueConstraint(fields=('snapshot', 'matrix_type', 'source_row', 'objective_code'), name='uniq_dashboard_objective_alignment'),
        ),
        migrations.AddConstraint(
            model_name='securityobjective',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_row'), name='uniq_security_objective_source_row'),
        ),
        migrations.AddConstraint(
            model_name='sgsimetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_row'), name='uniq_sgsi_metric_source_row'),
        ),
        migrations.AddConstraint(
            model_name='strategicfactor',
            constraint=models.UniqueConstraint(fields=('snapshot', 'factor_type', 'source_row'), name='uniq_dashboard_strategic_factor'),
        ),
    ]
