# Generated by Django 5.2.17 on 2026-09-18 10:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='#dcecf8', max_length=20)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.organizationalarea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('relation_type', models.CharField(choices=[('line', 'Jerárquica'), ('assistant', 'Asistente / apoyo'), ('staff', 'Staff / asesoría'), ('committee', 'Comité')], db_index=True, default='line', max_length=20)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('max_occupants', models.PositiveSmallIntegerField(default=1, help_text='0 = sin límite.')),
                ('is_critical', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('color', models.CharField(blank=True, help_text='Color opcional del cuadro, por ejemplo #d8edf9.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.organizationalarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['parent', 'sort_order'], name='org_pos_parent_order_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['area', 'is_active'], name='org_pos_area_active_idx'),
        ),
        migrations.AddIndex(
            model_name='positionassignment',
            index=models.Index(fields=['position', 'end_date'], name='org_asg_pos_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('user',), name='uniq_active_primary_org_assignment_user'),
        ),
    ]
