# Generated by Django 5.2.17 on 2026-09-18 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_documentsectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('mission_foda', 'Misión, Visión y FODA'), ('organization', 'Organigrama'), ('legal', 'Requisitos legales')], db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_location', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ContextDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(max_length=40)),
                ('original_name', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='context41.contextdocument')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context41_versions', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_current', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('requirement', models.TextField()),
                ('promulgated_by', models.CharField(blank=True, db_index=True, max_length=220)),
                ('location', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, db_index=True, max_length=220)),
                ('interested_parties', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_requirements', to='context41.contextdocumentversion')),
            ],
            options={
                'ordering': ('number', 'source_row'),
            },
        ),
        migrations.AddConstraint(
            model_name='contextdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'checksum_sha256'), name='uniq_ctx41_doc_checksum'),
        ),
        migrations.AddConstraint(
            model_name='contextdocumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='uniq_ctx41_current_ver'),
        ),
        migrations.AddIndex(
            model_name='legalrequirement',
            index=models.Index(fields=['version', 'status'], name='ctx41_legal_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalrequirement',
            constraint=models.UniqueConstraint(fields=('version', 'source_row'), name='uniq_ctx41_legal_row'),
        ),
    ]
