# Generated by Django 5.2.17 on 2026-09-18 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('authorization_authority', models.CharField(blank=True, help_text='Cargo o autoridad que puede aprobar o retirar el acceso.', max_length=200)),
                ('technical_implementer', models.CharField(blank=True, help_text='Cargo o responsable que implementa técnicamente el acceso.', max_length=200)),
                ('review_frequency', models.CharField(blank=True, help_text='Periodicidad de revisión definida por la fuente organizacional.', max_length=250)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sistema corporativo',
                'verbose_name_plural': 'Sistemas corporativos',
                'ordering': ('business_code',),
            },
        ),
        migrations.CreateModel(
            name='SystemAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('role_profile', models.CharField(blank=True, help_text='Rol o perfil que el usuario posee en el sistema corporativo.', max_length=200)),
                ('access_level', models.CharField(blank=True, max_length=200)),
                ('is_privileged', models.BooleanField(blank=True, help_text='NULL significa que la fuente todavía no confirma si es privilegiado.', null=True)),
                ('mfa_enabled', models.BooleanField(blank=True, help_text='NULL significa que la fuente todavía no confirma el estado de MFA.', null=True)),
                ('authorization_date', models.DateField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, help_text='Correo, acta, ticket u otra referencia que sustenta la autorización.', max_length=255)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('revoked', 'Revocado'), ('expired', 'Vencido')], default='requested', max_length=20)),
                ('last_review_at', models.DateField(blank=True, null=True)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_verified', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_system_accesses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='accounts.corporatesystem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a sistema',
                'verbose_name_plural': 'Accesos a sistemas',
                'ordering': ('user__business_code', 'system__business_code'),
            },
        ),
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('reviewed_at', models.DateField()),
                ('decision', models.CharField(choices=[('keep', 'Mantener'), ('modify', 'Modificar'), ('revoke', 'Revocar')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, help_text='Referencia al correo, archivo o evidencia que respalda la revisión.', max_length=255)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_access_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.systemaccess')),
            ],
            options={
                'verbose_name': 'Revisión de acceso',
                'verbose_name_plural': 'Revisiones de acceso',
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='corporatesystem',
            index=models.Index(fields=['name'], name='accounts_co_name_9222b7_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatesystem',
            index=models.Index(fields=['status'], name='accounts_co_status_db682d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['status'], name='accounts_sy_status_6ff94a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['is_privileged'], name='accounts_sy_is_priv_581b90_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['mfa_enabled'], name='accounts_sy_mfa_ena_5b7214_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['next_review_at'], name='accounts_sy_next_re_813230_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreview',
            index=models.Index(fields=['decision'], name='accounts_ac_decisio_66478f_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreview',
            index=models.Index(fields=['reviewed_at'], name='accounts_ac_reviewe_2d9b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreview',
            index=models.Index(fields=['next_review_at'], name='accounts_ac_next_re_220a27_idx'),
        ),
    ]
