# Generated by Django 5.2.17 on 2026-09-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_corporatesystem_systemaccess_accessreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemaccess',
            name='status_as_of',
            field=models.DateField(blank=True, help_text='Fecha en que la evidencia confirma el estado indicado.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source_document',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='source_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status_as_of',
            field=models.DateField(blank=True, help_text='Fecha en la que la fuente documental confirma el estado registrado.', null=True),
        ),
        migrations.AlterField(
            model_name='accessreview',
            name='evidence_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corporatesystem',
            name='review_frequency',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='systemaccess',
            name='approval_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemaccess',
            name='is_privileged',
            field=models.BooleanField(blank=True, help_text='NULL: la fuente no permite confirmar si el acceso es privilegiado.', null=True),
        ),
        migrations.AlterField(
            model_name='systemaccess',
            name='mfa_enabled',
            field=models.BooleanField(blank=True, help_text='NULL: la fuente no permite confirmar el estado de MFA.', null=True),
        ),
        migrations.AlterField(
            model_name='systemaccess',
            name='role_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemaccess',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('revoked', 'Revocado'), ('expired', 'Vencido'), ('unknown', 'Estado no confirmado')], default='requested', max_length=20),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['status_as_of'], name='accounts_sy_status__3b63e7_idx'),
        ),
    ]
