# Generated by Django 5.2.17 on 2026-09-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemaccess_status_as_of_user_source_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatesystem',
            name='status_as_of',
            field=models.DateField(blank=True, help_text='Fecha en la que la fuente documental confirma el estado registrado.', null=True),
        ),
        migrations.AlterField(
            model_name='corporatesystem',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('unknown', 'Estado no confirmado')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado'), ('inactive', 'Inactivo'), ('unknown', 'Estado no confirmado')], default='active', max_length=20),
        ),
    ]
