# Generated by Django 5.2.17 on 2026-09-18 13:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dashboard_live/source/%Y/%m/')),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version_label', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_current', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DashboardChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('entity_key', models.CharField(db_index=True, max_length=80)),
                ('field_name', models.CharField(max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('source_sheet', models.CharField(blank=True, max_length=160)),
                ('source_cell', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='dashboard_live.dashboarddataset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DashboardCellTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('entity_key', models.CharField(db_index=True, max_length=80)),
                ('field_name', models.CharField(max_length=80)),
                ('source_sheet', models.CharField(max_length=160)),
                ('source_cell', models.CharField(max_length=20)),
                ('source_formula', models.TextField(blank=True)),
                ('source_value', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell_traces', to='dashboard_live.dashboarddataset')),
            ],
            options={
                'ordering': ('source_sheet', 'source_cell'),
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_id', models.PositiveSmallIntegerField()),
                ('source_row', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('pdca_cycle', models.CharField(blank=True, max_length=10)),
                ('sgsi_process', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('responsible_text', models.CharField(blank=True, max_length=220)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('indicator', models.CharField(blank=True, max_length=80)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('current_text', models.CharField(blank=True, max_length=80)),
                ('excel_scale', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('source_compliance', models.CharField(blank=True, max_length=20)),
                ('action_plan', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sgsi_metrics', to='dashboard_live.dashboarddataset')),
                ('responsible_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sgsi_metrics', to='organization.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('metric_id',),
            },
        ),
        migrations.CreateModel(
            name='OesiMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_id', models.PositiveSmallIntegerField()),
                ('source_row', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('method', models.TextField(blank=True)),
                ('responsible_text', models.CharField(blank=True, max_length=220)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('indicator', models.CharField(blank=True, max_length=80)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('current_text', models.CharField(blank=True, max_length=80)),
                ('excel_scale', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('source_compliance', models.CharField(blank=True, max_length=20)),
                ('record_label', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oesi_metrics', to='dashboard_live.dashboarddataset')),
                ('responsible_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_oesi_metrics', to='organization.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('metric_id',),
            },
        ),
        migrations.CreateModel(
            name='SecurityObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('source_column', models.CharField(max_length=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_objectives', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='StakeholderRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.PositiveSmallIntegerField()),
                ('stakeholder', models.CharField(blank=True, max_length=220)),
                ('requirement', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_requirements', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_row',),
            },
        ),
        migrations.CreateModel(
            name='RequirementOsiAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(blank=True, choices=[('', 'Sin relación'), ('P', 'Primario'), ('S', 'Secundario')], default='', max_length=1)),
                ('source_cell', models.CharField(max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_osi_alignments', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('security_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_alignments', to='dashboard_live.securityobjective')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_alignments', to='dashboard_live.stakeholderrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matrix_type', models.CharField(choices=[('MEFI', 'MEFI'), ('MEFE', 'MEFE')], db_index=True, max_length=10)),
                ('group', models.CharField(choices=[('strength', 'Fortalezas'), ('weakness', 'Debilidades'), ('opportunity', 'Oportunidades'), ('threat', 'Amenazas')], db_index=True, max_length=20)),
                ('source_row', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('classification', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_factors', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('matrix_type', 'source_row'),
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('source_row', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_objectives', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_row',),
            },
        ),
        migrations.CreateModel(
            name='OeeOsiAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(blank=True, choices=[('', 'Sin relación'), ('P', 'Primario'), ('S', 'Secundario')], default='', max_length=1)),
                ('source_cell', models.CharField(max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oee_osi_alignments', to='dashboard_live.dashboarddataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('security_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_alignments', to='dashboard_live.securityobjective')),
                ('strategic_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_alignments', to='dashboard_live.strategicobjective')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dashboarddataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_dash_live_current'),
        ),
        migrations.AddConstraint(
            model_name='dashboardmetric',
            constraint=models.UniqueConstraint(fields=('dataset', 'metric_id'), name='uniq_dash_live_sgsi_metric'),
        ),
        migrations.AddConstraint(
            model_name='oesimetric',
            constraint=models.UniqueConstraint(fields=('dataset', 'metric_id'), name='uniq_dash_live_oesi_metric'),
        ),
        migrations.AddConstraint(
            model_name='securityobjective',
            constraint=models.UniqueConstraint(fields=('dataset', 'code'), name='uniq_dash_live_osi'),
        ),
        migrations.AddConstraint(
            model_name='stakeholderrequirement',
            constraint=models.UniqueConstraint(fields=('dataset', 'source_row'), name='uniq_dash_live_req_row'),
        ),
        migrations.AddConstraint(
            model_name='requirementosialignment',
            constraint=models.UniqueConstraint(fields=('dataset', 'requirement', 'security_objective'), name='uniq_dash_live_req_osi'),
        ),
        migrations.AddConstraint(
            model_name='strategicfactor',
            constraint=models.UniqueConstraint(fields=('dataset', 'matrix_type', 'source_row'), name='uniq_dash_live_factor'),
        ),
        migrations.AddConstraint(
            model_name='strategicobjective',
            constraint=models.UniqueConstraint(fields=('dataset', 'code'), name='uniq_dash_live_oee'),
        ),
        migrations.AddConstraint(
            model_name='oeeosialignment',
            constraint=models.UniqueConstraint(fields=('dataset', 'strategic_objective', 'security_objective'), name='uniq_dash_live_oee_osi'),
        ),
    ]
