# Generated by Django 5.2.17 on 2026-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetric',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='oesimetric',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='oesimetric',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='securityobjective',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='securityobjective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='stakeholderrequirement',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='stakeholderrequirement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='strategicfactor',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='strategicfactor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='created_in_system',
            field=models.BooleanField(default=False, verbose_name='Creado en el sistema'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Vigente'),
        ),
    ]
