# Generated by Django 5.2.17 on 2026-09-16 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('controls', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('process', models.CharField(db_index=True, max_length=160)),
                ('scenario', models.TextField()),
                ('threat', models.CharField(blank=True, max_length=255)),
                ('vulnerability', models.CharField(blank=True, max_length=255)),
                ('consequence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identificado'), ('treatment', 'En tratamiento'), ('accepted', 'Aceptado'), ('closed', 'Cerrado')], db_index=True, default='identified', max_length=20)),
                ('identified_at', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='assets.asset')),
                ('controls', models.ManyToManyField(blank=True, related_name='risks', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_at', models.DateTimeField()),
                ('probability', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('inherent_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('residual_probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assessed_at',),
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(max_length=60)),
                ('action', models.TextField()),
                ('resources', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_risk_treatments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatments', to='documents.evidence')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatments', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
