# Generated by Django 5.2.17 on 2026-09-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='risk',
            name='event',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='existing_controls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='origin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='risk',
            name='owner_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to='organization.position'),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='residual_impact',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='residual_probability',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='source_end',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='source_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatments', to=settings.AUTH_USER_MODEL),
        ),
    ]
