# Generated by Django 5.2.17 on 2026-09-18 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SGSISection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('manual_version', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documents.sgsisection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección SGSI',
                'verbose_name_plural': 'Secciones SGSI',
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='sgsi_sections',
            field=models.ManyToManyField(blank=True, help_text='Numerales del Manual del SGSI sustentados por este documento.', related_name='documents', to='documents.sgsisection'),
        ),
        migrations.CreateModel(
            name='SourceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('original_path', models.TextField(blank=True, help_text='Ruta original dentro del ZIP o repositorio.')),
                ('source_archive', models.CharField(blank=True, help_text='Nombre del ZIP u origen del que provino.', max_length=255)),
                ('source_kind', models.CharField(choices=[('zip_member', 'Archivo extraído de ZIP'), ('standalone', 'Archivo proporcionado directamente'), ('generated', 'Archivo generado'), ('unknown', 'Origen no determinado')], default='unknown', max_length=30)),
                ('extension', models.CharField(blank=True, max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=160)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='source_artifacts/%Y/%m/')),
                ('source_verified', models.BooleanField(default=False)),
                ('quality_status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('verified', 'Verificado'), ('warning', 'Con observaciones'), ('duplicate', 'Duplicado'), ('invalid', 'Dato o archivo inválido')], db_index=True, default='pending', max_length=30)),
                ('quality_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_copies', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo fuente',
                'verbose_name_plural': 'Inventario maestro de archivos',
                'ordering': ('source_archive', 'original_path', 'original_name'),
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='source_artifact',
            field=models.ForeignKey(blank=True, help_text='Archivo original del inventario maestro del cual provino esta versión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to='documents.sourceartifact'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_artifact',
            field=models.ForeignKey(blank=True, help_text='Archivo original del inventario maestro que sustenta esta evidencia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='documents.sourceartifact'),
        ),
        migrations.AddIndex(
            model_name='sourceartifact',
            index=models.Index(fields=['source_kind'], name='documents_s_source__962d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceartifact',
            index=models.Index(fields=['quality_status'], name='documents_s_quality_5bdb48_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceartifact',
            index=models.Index(fields=['extension'], name='documents_s_extensi_2d4986_idx'),
        ),
    ]
