# Generated by Django 5.2.17 on 2026-09-18 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_sgsisection_document_sgsi_sections_sourceartifact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('original_path', models.TextField(blank=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('verified', 'Verificado'), ('warning', 'Con observaciones')], db_index=True, default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paquete fuente',
                'verbose_name_plural': 'Paquetes fuente',
                'ordering': ('original_name',),
            },
        ),
        migrations.AddField(
            model_name='sourceartifact',
            name='source_package',
            field=models.ForeignKey(blank=True, help_text='Paquete ZIP o lote documental del cual provino el archivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='documents.sourcepackage'),
        ),
    ]
