# Generated by Django 5.2.17 on 2026-09-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_sourcepackage_sourceartifact_source_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepackage',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Paquete previamente registrado con el mismo contenido documental.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_packages', to='documents.sourcepackage'),
        ),
        migrations.AddField(
            model_name='sourcepackage',
            name='manifest_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 calculado sobre el manifiesto normalizado de archivos internos.', max_length=64),
        ),
        migrations.AlterField(
            model_name='sourcepackage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de revisión'), ('verified', 'Verificado'), ('warning', 'Con observaciones'), ('duplicate', 'Contenido duplicado')], db_index=True, default='pending', max_length=30),
        ),
    ]
