# Generated by Django 5.2.17 on 2026-09-18 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_sourcepackage_duplicate_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceArtifactClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle_hint', models.CharField(choices=[('vigente', 'Vigente'), ('no_vigente', 'No vigente'), ('borrador', 'Borrador'), ('historico', 'Histórico'), ('sin_clasificar', 'Sin clasificar')], db_index=True, default='sin_clasificar', max_length=32)),
                ('family_hint', models.CharField(choices=[('politica', 'Política'), ('manual', 'Manual'), ('procedimiento', 'Procedimiento'), ('instructivo', 'Instructivo'), ('guia', 'Guía'), ('estandar', 'Estándar'), ('matriz', 'Matriz'), ('dashboard', 'Dashboard'), ('formato', 'Formato'), ('plantilla', 'Plantilla'), ('registro', 'Registro'), ('acta', 'Acta'), ('reporte', 'Reporte'), ('informe', 'Informe'), ('evidencia', 'Evidencia'), ('hoja_calculo', 'Hoja de cálculo'), ('pdf_otro', 'PDF - otro'), ('documento_texto', 'Documento de texto'), ('presentacion', 'Presentación'), ('imagen', 'Imagen'), ('plantilla_reporte', 'Plantilla de reporte'), ('binario_tecnico', 'Binario técnico'), ('script_config', 'Script / configuración'), ('texto_tecnico', 'Texto técnico'), ('archivo_comprimido', 'Archivo comprimido'), ('otro', 'Otro')], db_index=True, default='otro', max_length=40)),
                ('area_hint', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sgsi_relevance', models.CharField(choices=[('nucleo_sgsi', 'Núcleo SGSI'), ('soporte_sgsi', 'Soporte / evidencia SGSI'), ('operacional', 'Operacional'), ('tecnico', 'Técnico'), ('sin_clasificar', 'Sin clasificar')], db_index=True, default='sin_clasificar', max_length=32)),
                ('is_document_candidate', models.BooleanField(db_index=True, default=False)),
                ('is_evidence_candidate', models.BooleanField(db_index=True, default=False)),
                ('is_dashboard_candidate', models.BooleanField(db_index=True, default=False)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confianza de clasificación automática entre 0 y 100.')),
                ('rule_version', models.CharField(db_index=True, default='2026.09-v1', max_length=32)),
                ('classification_reason', models.TextField(blank=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='classification', to='documents.sourceartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clasificación de artefacto fuente',
                'verbose_name_plural': 'clasificaciones de artefactos fuente',
                'ordering': ['artifact__original_path', 'artifact__original_name'],
            },
        ),
    ]
