# Generated by Django 5.2.17 on 2026-09-18 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_sourceartifactclassification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_identity_key',
            field=models.CharField(blank=True, db_index=True, help_text='Huella estable de la identidad documental importada. Permite reejecutar la promoción sin duplicar documentos.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsable documental. Puede quedar pendiente durante una importación histórica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('active', 'Vigente / Activo'), ('inactive', 'Inactivo'), ('obsolete', 'Obsoleto')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('active', 'Vigente / Activo'), ('inactive', 'Inactivo'), ('obsolete', 'Obsoleto')], default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DocumentImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_type', models.CharField(choices=[('version_conflict', 'Conflicto de versión'), ('ambiguous_version', 'Versión ambigua'), ('ambiguous_group', 'Agrupación ambigua'), ('source_missing', 'Fuente faltante'), ('other', 'Otra incidencia')], db_index=True, default='other', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('resolved', 'Resuelta'), ('ignored', 'Ignorada justificadamente')], db_index=True, default='open', max_length=20)),
                ('group_key', models.CharField(blank=True, db_index=True, help_text='Huella de la identidad documental detectada durante la promoción/importación.', max_length=64)),
                ('version_label', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_issues', to='documents.document')),
                ('source_artifacts', models.ManyToManyField(blank=True, related_name='document_import_issues', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incidencia de importación documental',
                'verbose_name_plural': 'incidencias de importación documental',
                'ordering': ('status', 'issue_type', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersionRepresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representation_type', models.CharField(choices=[('published_pdf', 'PDF publicado'), ('editable_source', 'Fuente editable'), ('spreadsheet', 'Hoja de cálculo'), ('presentation', 'Presentación'), ('other', 'Otra representación')], db_index=True, default='other', max_length=32)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Indica la representación principal de la versión (por ejemplo, PDF publicado).')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representations', to='documents.documentversion')),
                ('source_artifact', models.OneToOneField(help_text='Artefacto fuente verificado que contiene esta representación física de la versión.', on_delete=django.db.models.deletion.PROTECT, related_name='version_representation', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'representación de versión documental',
                'verbose_name_plural': 'representaciones de versiones documentales',
                'ordering': ('document_version__document__code', 'document_version__version', '-is_primary', 'representation_type'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('document_version',), name='uniq_primary_representation_per_version')],
            },
        ),
    ]
