# Generated by Django 5.2.17 on 2026-09-18 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_source_identity_key_alter_document_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('auto', 'Regla automática'), ('manual', 'Asignación manual'), ('manual_reference', 'Referencia explícita del Manual SGSI')], db_index=True, default='auto', max_length=24)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confianza de la asignación entre 0 y 100.')),
                ('rule_version', models.CharField(db_index=True, default='2026.09-section-v1', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_assignments', to='documents.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_assignments', to='documents.sgsisection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación documental a sección SGSI',
                'verbose_name_plural': 'asignaciones documentales a secciones SGSI',
                'ordering': ('section__sort_order', 'section__code', 'document__code'),
                'constraints': [models.UniqueConstraint(fields=('document', 'section'), name='uniq_document_sgsi_section_assignment')],
            },
        ),
    ]
