# Generated by Django 5.2.17 on 2026-09-18 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context42Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('interested', 'Partes interesadas'), ('legal', 'Lista de requisitos legales')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Context42DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='context42/')),
                ('original_name', models.CharField(max_length=255)),
                ('version_label', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context42_versions_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='context42.context42document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context42_versions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterestedPartyRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('party_name', models.CharField(db_index=True, max_length=180)),
                ('need', models.TextField()),
                ('expectation', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_rows', to='context42.context42documentversion')),
            ],
            options={
                'ordering': ('source_row', 'party_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LegalRequirementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('item_no', models.CharField(blank=True, max_length=30)),
                ('requirement', models.TextField()),
                ('promulgated_by', models.CharField(blank=True, max_length=200)),
                ('location', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=200)),
                ('stakeholders', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_rows', to='context42.context42documentversion')),
            ],
            options={
                'ordering': ('source_row', 'id'),
            },
        ),
    ]
