# Generated by Django 5.2.17 on 2026-09-18 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('controls', '0003_controldocumentassignment'),
        ('documents', '0007_documentsectionassignment'),
        ('organization', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('strategic', 'Proceso estratégico'), ('operational', 'Proceso operativo'), ('support', 'Proceso de apoyo')], db_index=True, max_length=20, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('color', models.CharField(blank=True, default='#dcecf8', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProcessNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('x', models.PositiveSmallIntegerField(default=100)),
                ('y', models.PositiveSmallIntegerField(default=100)),
                ('is_in_scope', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='processes', to='assets.asset')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.processcategory')),
                ('controls', models.ManyToManyField(blank=True, related_name='processes', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='processes', to='documents.document')),
                ('involved_areas', models.ManyToManyField(blank=True, related_name='processes', to='organization.organizationalarea')),
                ('involved_positions', models.ManyToManyField(blank=True, related_name='involved_processes', to='organization.position')),
                ('owner_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_processes', to='organization.position')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_processes', to=settings.AUTH_USER_MODEL)),
                ('risks', models.ManyToManyField(blank=True, related_name='processes', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category__sort_order', 'y', 'x', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProcessReferenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('kind', models.CharField(choices=[('scope', 'Documento sobre el alcance del SGSI'), ('map', 'Mapa de procesos')], db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProcessReferenceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='processes/references/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='processes.processreferencedocument')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_current', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProcessRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('flow', 'Flujo / interacción'), ('support', 'Apoyo'), ('governance', 'Gobierno / dirección'), ('reference', 'Referencia')], db_index=True, default='flow', max_length=20)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='processes.processnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='processes.processnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source__name', 'target__name'),
            },
        ),
        migrations.CreateModel(
            name='ProcessCategoryRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('flow', 'Flujo / interacción'), ('support', 'Apoyo'), ('governance', 'Gobierno / dirección'), ('reference', 'Referencia')], default='support', max_length=20)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_category_relations', to='processes.processcategory')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_category_relations', to='processes.processcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='uniq_process_category_relation')],
            },
        ),
        migrations.AddIndex(
            model_name='processnode',
            index=models.Index(fields=['category', 'is_active'], name='proc_node_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='processnode',
            index=models.Index(fields=['is_in_scope', 'is_active'], name='proc_node_scope_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='processreferenceversion',
            constraint=models.UniqueConstraint(fields=('document', 'checksum_sha256'), name='uniq_process_ref_checksum'),
        ),
        migrations.AddConstraint(
            model_name='processreferenceversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='uniq_process_ref_current'),
        ),
        migrations.AddConstraint(
            model_name='processrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='uniq_process_relation'),
        ),
    ]
