# Generated by Django 5.2.17 on 2026-09-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processnode',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Proceso externo'),
        ),
    ]
