# Generated by Django 5.2.17 on 2026-09-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('processes', '0002_processnode_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='processnode',
            name='primary_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_processes', to='organization.organizationalarea', verbose_name='Área responsable'),
        ),
    ]
