# Generated by Django 5.2.17 on 2026-09-18 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('documents', '0007_documentsectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_clauses', to='controls.controlframework')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='controls.isoclause')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iso_clauses', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('framework__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ISODataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_type', models.CharField(choices=[('source_discrepancy', 'Discrepancia en fuente'), ('unmatched_control', 'Control no conciliado'), ('control_count', 'Cantidad de controles'), ('clause_mapping', 'Mapeo de cláusula'), ('other', 'Otra')], db_index=True, default='other', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('error', 'Error')], db_index=True, default='warning', max_length=16)),
                ('description', models.TextField()),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iso_quality_issues', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('resolved', 'severity', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ISORequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_label', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('supporting_reference', models.TextField(blank=True)),
                ('is_clause_heading', models.BooleanField(db_index=True, default=False)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='controls.isoclause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_requirements', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('clause__code', 'source_row'),
            },
        ),
        migrations.CreateModel(
            name='ControlSupportReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporting_reference', models.TextField(blank=True)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('raw_control_code', models.CharField(blank=True, max_length=30)),
                ('raw_control_name', models.CharField(blank=True, max_length=255)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_references', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_support_references', to='documents.sourceartifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('control__code', 'source_row'),
                'constraints': [models.UniqueConstraint(fields=('control', 'source_artifact', 'source_sheet', 'source_row'), name='uniq_control_support_source_row')],
            },
        ),
        migrations.AddConstraint(
            model_name='isoclause',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uniq_framework_iso_clause'),
        ),
        migrations.AddConstraint(
            model_name='isorequirement',
            constraint=models.UniqueConstraint(fields=('source_artifact', 'source_sheet', 'source_row'), name='uniq_iso_requirement_source_row'),
        ),
    ]
