# Generated by Django 5.2.17 on 2026-09-18 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_isoclause_isodataqualityissue_isorequirement_and_more'),
        ('documents', '0007_documentsectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDocumentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('exact_reference', 'Referencia textual exacta'), ('fuzzy_reference', 'Referencia textual normalizada'), ('manual', 'Asignación manual')], db_index=True, default='exact_reference', max_length=24)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confianza de la vinculación entre 0 y 100.')),
                ('matched_fragment', models.TextField(blank=True, help_text='Fragmento de la fuente que sustentó la vinculación.')),
                ('matched_alias', models.CharField(blank=True, help_text='Título o nombre de archivo utilizado para el emparejamiento.', max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('rule_version', models.CharField(db_index=True, default='2026.09-control-doc-v1', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_assignments', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_assignments', to='documents.document')),
                ('support_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_assignments', to='controls.controlsupportreference')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación control-documento',
                'verbose_name_plural': 'asignaciones control-documento',
                'ordering': ('control__code', '-confidence', 'document__code'),
                'constraints': [models.UniqueConstraint(fields=('control', 'document'), name='uniq_control_document_assignment')],
            },
        ),
    ]
