# Generated by Django 5.2.17 on 2026-09-16 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('controls', '0001_initial'),
        ('documents', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('incident_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(db_index=True, default='reported', max_length=40)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affected_incidents', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='assets.asset')),
                ('controls', models.ManyToManyField(blank=True, related_name='incidents', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(blank=True, related_name='incidents', to='documents.evidence')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_incidents', to=settings.AUTH_USER_MODEL)),
                ('risks', models.ManyToManyField(blank=True, related_name='incidents', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('action', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_events', to='documents.evidence')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='incidents.incident')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source', models.CharField(max_length=160)),
                ('cve', models.CharField(blank=True, db_index=True, max_length=30)),
                ('cvss', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, default='open', max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('solution', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerabilities', to='assets.asset')),
                ('controls', models.ManyToManyField(blank=True, related_name='vulnerabilities', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(blank=True, related_name='vulnerabilities', to='documents.evidence')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerabilities', to=settings.AUTH_USER_MODEL)),
                ('risks', models.ManyToManyField(blank=True, related_name='vulnerabilities', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
